### PR TITLE
Extra sensors

### PR DESCRIPTION
**Pull request by chribba021**
Added extra sensor entities for the current room temperature for use in cards or helpers.
Will also add humidity and floor temperatur if the Thermostat reports it.

Device now includes sensors:
Device

Creates separate senor entities for temp, 
(wanted it to make a helper with arimetic median for average indoor temp in the house)
enteties

**Added extra debug logging, will list termostats and name on** 
[custom_components.uponor] Unloading setup entry:
e.g: data: {'host': '192.168.1.131', 'name': 'Uponor', 'c1_t1': 'Guest Room', 'c1_t2': 'Office', 
DEBUG (MainThread) [custom_components.uponor] Unload status for Uponor platforms: True
DEBUG (MainThread) [custom_components.uponor.sensor] Adding sensors for Guest Room (thermostat ID: C1_T1)
DEBUG (MainThread) [custom_components.uponor.sensor] Total amount of sensors added: xx

### CODE REVIEW

**Comment by NewsGuyTor** [comment]
Cool that you improved mine and Valentin's code from #57, but some mention/credit would have been nice.

EDIT: Since you closed this PR for some reason, I've added your improvements back into the PR, with credits.

**Comment by chribba021** [comment]
> Cool that you improved mine and Valentin's code from #57, but some mention/credit would have bee

**Comment by NewsGuyTor** [comment]
You know that you can edit stuff, right? ;)

**Comment by chribba021** [comment]
Hi!, No idea what happened, I also had no intention to steal any credit for
what you guys started. I would rather prefer to maybe do pulls on your
pulls? I'm really new to github so don't understand the best practices and
how the correct way is to work on "open source" byt eager to learn.
I see that I may have closed my commit by mistake,

Should I open it or should I do updates in one of your merges instead?
Any pointing in the correct way of doing things is appreciated :)

/Christian

**Pull request closed without merging**
