### PR TITLE
Trying to solves asev#52

### PR DESCRIPTION
**Pull request by dave-code-ruiz**
Trying to solves asev#52

### CODE REVIEW

**Comment by ErikSabel** [comment]
[home-assistant_uponor_2024-07-04T12-23-36.024Z.log](https://github.com/user-attachments/files/16098830/home-assistant_uponor_2024-07-04T12-23-36.024Z.log)

Hopefully this goes in the right direction with this logging. If something else needed, let me know (and also where to find as I am kind of new in HA and no software/IT background)

**Comment by dave-code-ruiz** [comment]
> [home-assistant_uponor_2024-07-04T12-23-36.024Z.log](https://github.com/user-attachments/files/16098830/home-assistant_uponor_2024-07-04T12-23-36.024Z.log)
> 
> Hopefully this goes in the right direction with this logging. If something else needed, let me know (and also where to find as I am kind of new in HA and no software/IT background)

You need to change files climate.py and __init__,py in your custom_components/uponor folder with my files in this PR and restart, then post new homeassistant log file

**Comment by ErikSabel** [comment]
After change the files climate and init, the intergration doesn't start-up anymore. Can't run any debug file as it is not available

**Comment by dave-code-ruiz** [comment]
Ok , log it shows all work fine.

If integration work fine , and update states, only wait possible api errors or warnings

tomorrow, I send you new code to solves this warning:

Detected that custom integration 'uponor' calls async_forward_entry_setup for integration, uponor with title: Uponor

**Comment by ErikSabel** [comment]
It's update with the suggestion above, but it stopped again after approx. 1 hour it seems.
See the log file
[home-assistant_uponor_2024-07-05T06-31-19.009Z.log](https://github.com/user-attachments/files/16105809/home-assistant_uponor_2024-07-05T06-31-19.009Z.log)

**Comment by dave-code-ruiz** [comment]
Ok, i commit new changes to files, You need to change files climate.py, switch.py and init,py in your custom_components/uponor folder with my files in this PR and restart, then post new homeassistant log file

Thanks

**Comment by aivarasSevelevicius** [comment]
Thank you for the contribution ❤️

**Comment by dave-code-ruiz** [comment]
For thanks for collaboration:

<a href="https://www.buymeacoffee.com/davecoderuiz" target="_blank">Buy Me A Coffee</a>

**Comment by ErikSabel** [comment]
After 11 hours, it's still working! So far so good 👍

**Pull request merged**
